# Initialize message templates
from .messages import (
    LOGIN_REQUEST_MESSAGE,
    OTP_SENT_MESSAGE,
    INVALID_PHONE_NUMBER_MESSAGE,
    INVALID_OTP_MESSAGE,
    LOGIN_SUCCESS_MESSAGE,
    LOGIN_FAILURE_MESSAGE,
    PASSWORD_REQUIRED_MESSAGE,
    PASSWORD_FAILURE_MESSAGE,
    NO_GROUPS_FOUND_MESSAGE,
    INVALID_INPUT_MESSAGE,
    GROUP_PAGE_INSTRUCTION,
    INVALID_PAGE_NUMBER_MESSAGE,
    OTP_SENT_MESSAGE,
)

